// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sandwich_cluster_logit_accumulate
List sandwich_cluster_logit_accumulate(NumericMatrix X, IntegerVector cluster_index, int n_clusters, NumericVector fitted_values, NumericVector outcome);
RcppExport SEXP _LAGOtrials_sandwich_cluster_logit_accumulate(SEXP XSEXP, SEXP cluster_indexSEXP, SEXP n_clustersSEXP, SEXP fitted_valuesSEXP, SEXP outcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_index(cluster_indexSEXP);
    Rcpp::traits::input_parameter< int >::type n_clusters(n_clustersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fitted_values(fitted_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(sandwich_cluster_logit_accumulate(X, cluster_index, n_clusters, fitted_values, outcome));
    return rcpp_result_gen;
END_RCPP
}
// sandwich_hc0_logit_accumulate
List sandwich_hc0_logit_accumulate(NumericMatrix X, NumericVector fitted_values, NumericVector outcome);
RcppExport SEXP _LAGOtrials_sandwich_hc0_logit_accumulate(SEXP XSEXP, SEXP fitted_valuesSEXP, SEXP outcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fitted_values(fitted_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(sandwich_hc0_logit_accumulate(X, fitted_values, outcome));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LAGOtrials_sandwich_cluster_logit_accumulate", (DL_FUNC) &_LAGOtrials_sandwich_cluster_logit_accumulate, 5},
    {"_LAGOtrials_sandwich_hc0_logit_accumulate", (DL_FUNC) &_LAGOtrials_sandwich_hc0_logit_accumulate, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LAGOtrials(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
