# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sandwich_cluster_logit_accumulate <- function(X, cluster_index, n_clusters, fitted_values, outcome, prior_weights = NULL) {
    .Call(`_LAGOtrials_sandwich_cluster_logit_accumulate`, X, cluster_index, n_clusters, fitted_values, outcome, prior_weights)
}

sandwich_hc0_logit_accumulate <- function(X, fitted_values, outcome, prior_weights = NULL) {
    .Call(`_LAGOtrials_sandwich_hc0_logit_accumulate`, X, fitted_values, outcome, prior_weights)
}

